variable "zone_id" {
  type        = string
  default     = "cn-beijing-l"
  description = "Primary availability zone ID (cn-beijing-l for TDX/TEE instances)"
}

variable "vpc_cidr" {
  type        = string
  default     = "10.0.0.0/16"
  description = "VPC CIDR block"
}

variable "vswitch_cidr" {
  type        = string
  default     = "10.0.1.0/24"
  description = "VSwitch CIDR block"
}

variable "deploy_trustee" {
  type        = bool
  default     = false
  description = "Whether to deploy the central Trustee instance (SECRET_MODE=trustee)"
}

variable "trustee_private_ip" {
  type        = string
  default     = "10.0.1.10"
  description = "Trustee instance private IP (must be within vswitch_cidr)"
}

variable "image_type" {
  type        = string
  default     = "prod"
  description = "Image type to use: 'prod' or 'debug'"
  validation {
    condition     = contains(["prod", "debug"], var.image_type)
    error_message = "image_type must be either 'prod' or 'debug'"
  }
}

variable "security_group_allowed_cidr" {
  type        = string
  default     = "0.0.0.0/0"
  description = "Source IP range allowed to access SSH and service ports"
}

variable "trustee_instance_type" {
  type        = string
  default     = "ecs.g7.xlarge"
  description = "Trustee ECS instance type (used when deploy_trustee = true)"
}

variable "project_name" {
  type        = string
  default     = "cai"
  description = "Project name for resource naming"
}

# ---------------------------------------------------------------------------
# Service profiles (populated from image/profiles/*/profile.json)
# ---------------------------------------------------------------------------
variable "services" {
  type = map(object({
    ip            = string
    instance_type = string
    tdx           = optional(bool, true)
    disk_size     = optional(number, 200)
    sg_ports      = list(string)
    image_file    = string
  }))
  default     = {}
  description = "Map of service profiles to deploy. Keys are profile names (e.g. 'openclaw', 'mcp'). Auto-generated by Makefile from profile.json files."
}
