# Cryptpilot FDE Configuration for cai
# rootfs: dm-verity protected (no encryption) with rw delta layer
# data: OTP (one-time password) encryption

[rootfs]
delta_location = "disk-persist"    # rootfs is read-only with a persist writable delta layer on delta volume on disk

[delta]
integrity = false      # No integrity check for delta volume

[delta.encrypt.exec]
# Read disk passphrase from CAI secret staging directory (initrd phase)
command = "cat"
args = ["/run/cai/secrets/disk_key"]

